---
- import_tasks: setup.yml

- name: "Setup recordings"
  ansible.builtin.import_tasks: recording.yml
    apply:
      tags: recording
  when:
    - scalelite_recording is defined and scalelite_recording | bool
  tags:
    - recording
