- name: "Create scalelite tmp-dir"
  ansible.builtin.file:
    path: "/mnt/scalelite-recordings/var/bigbluebutton"
    state: directory
    mode: '0755'
    owner: "bigbluebutton"
    group: "scalelite-spool"
  tags:
    - recording_tmp_dir

- name: "Create scalelite tmp-dir"
  ansible.builtin.file:
    path: "/mnt/scalelite-recordings/var/bigbluebutton/{{ item }}"
    state: directory
    mode: '0755'
    owner: "bigbluebutton"
    group: "scalelite-spool"
  with_items:
    - recording
    - recording/scalelite
    - published
    - unpublished
  tags:
    - recording_tmp_dir_structure
